### PR TITLE
Vite Setup and Folder Structure

### PR DESCRIPTION
**Pull request by efezinoidisi**
## Changes in this PR

This PR aims to establish a solid foundation for our frontend development. Here's an overview of the changes:

Folder Structure:

I've organized the project into clear directories like "pages" "hooks" and "components" to keep our codebase organized.

Dependencies:

I've added the initial dependencies to the package.json file. Please remember to periodically update dependencies using npm update or yarn upgrade.

### CODE REVIEW

**Comment by Abiorh001** [comment]
you should make a branch for frontend and push your code their so when anyone is done with any module we will test with backend branch too if all works we will push both to main and continue like that. so we won't run to issue with the main since we don't have a test script available

**Comment by lazee7** [comment]
This is the frontend branch though.

**Comment by Abiorh001** [comment]
ok have seen it now just leave it for now lets continue our work we only push to main after we have test for each module working well

**Comment by efezinoidisi** [comment]
This is the frontend branch. backend can also have their branch and folders. If we don't merge to main regularly the commit history will be a mess. so after making changes on frontend or backend we can periodically merge to main to avoid too much diverging of the branches. @Abiorh001

**Pull request merged**
